version: "3.8"

services:
  backend:
    build: ./backend
    container_name: desafio_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    container_name: desafio_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/www:ro
    depends_on:
      - backend
